include:
  - .gitlab-ci-test.yml
  - .gitlab-ci-build.yml

image: $REGISTRY_DEVELOPMENT/build-env:latest

variables:
  AWS_REGION: eu-central-1
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://localhost:2375/
  NODE_OPTIONS: --max-old-space-size=4096
  TOOL_NODE_FLAGS: --max-old-space-size=4096

default:
  before_script:
    - cachix use ge-devops
    - nix-shell .gitlab-ci/shell.nix
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - test
  - build
