apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: app
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0 # Avoid Terminating and ContainerCreating at the same time
  selector:
    matchLabels:
      app: app

  # Pod template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: grassrootseconomics/server:591528b
          resources:
            limits:
              cpu: "0.2"
              memory: 2048Mi
            requests:
              cpu: "0.15"
              memory: 1536Mi
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: aws
          ports:
            - containerPort: 3031
              name: stats
            - containerPort: 9000
              name: app
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 3031
      protocol: TCP
      name: stats
    - port: 9000
      protocol: TCP
      name: app
  selector:
    app: app
