apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app

  # Pod template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: grassrootseconomics/server:02fb5dd
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: aws
          ports:
            - containerPort: 3031
              name: stats
            - containerPort: 9000
              name: app
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 3031
      protocol: TCP
      name: stats
    - port: 9000
      protocol: TCP
      name: app
  selector:
    app: app
