apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: default
spec:
  storageClassName: csi-packet-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
